### ISSUE TITLE
TODO

### ISSUE THREAD

**Issue by tsutaj** [tsutaj/statements-manager#3]
- [x] #4 良いテストケース指定方法
  - `{@samples.sample_00_in}` とか `{@samples.sample_01_in}` とかやってたら結局目 diff 失敗してどこかでミスりそう、いい方法ないんか？
  - 出力のみの場合や、インタラクティブなどの特殊ケースにも対応させる仕組みも必要
- [x] #7 CUI 上で情報をいい感じに出す
  - 指定されたテストケースファイルが実際に存在しなくても警告が出ない (？)
    - これ以外にも、ファイル読み込み時に何も言ってくれない箇所はいっぱいある
  - 多分その他いろいろと不十分なはず
  - logger をもうちょい真面目に使いたい
- [x] #11 エラー処理
  - プロジェクトの出力の上書きを許容するオプション (`allow_rewrite` みたいなやつを config で指定するかんじ)
  - 同一プロジェクト内に同一の問題 ID が来たら怒ってほしい
  - ディレクトリ名にできないような問題 ID を指定されたら怒ってほしい
- [x] #6 `params.h` (制約がまとまっているファイル) を自動生成してほしい
  - yosupo judge にあるようなやつを吐いたら便利そう？どこに吐いてほしいかはよくわからんけど、指定できるようにできたらいい？
  - 非 ASCII 文字を含むような変数 (`入力は全て整数` とか) は無視でいいかなあ
  - 抽象化しておくといろんな言語で制約ファイルが吐けてうれしそう (適当)
- [x] #24 TeX 関係
  - バックスラッシュ `\` は二重にしないと (つまり `\\`) うまくいかない。KaTeX の仕様？？
- [ ] ~~#13 サンプルと問題文の更新日比較~~
  - (サンプルの更新日時) > (問題文の更新日時) であれば (サンプルのほうが新しいという意味) 警告を出す
  - つらそうなので今はやらない
- [x] #8 フォーマット関係
  - CI でチェックするようにする (今の所適当にやっちゃってるので・・・)
- [x] #15 デフォルトの設定を `.toml` で用意せず別の場所に置く
  - 適当にモジュールにすると良いと思う
- [x] #17 jinja2 において、attribute が存在しなかった時に怒る
- [x] #19 リリース (beta)

**Comment by tsutaj** [comment]
そもそもインタラクティブなら表を書かないといけないはず。(例えば下に書いた感じのやつ)

インタラクティブの場合は、この表がかいてある markdown ファイルを指定してもらえばいい？

|Output|Judge|
|---|---|
||```5```|
|```3 2```<br />```1 2 3 4 5```||
||```-1```|

**Comment by tsutaj** [comment]
入力が与えられない問題も存在するので、必ずしも入力・出力がどちらも存在するわけではない。  
(ところで出力がない問題はあるのか？)

サンプルはこんな感じで指定してもらうのがいいかな・・・

```toml
[problem.samples]
    id = "sample_00"
    type = "default" # "default", "input-only", "output-only", "interactive"
    input_path = "path/to/sample.in" # "default" および "input-only" で必要
    output_path = "path/to/sample.out" # "default" および "output-only" で必要
    interactive_path = "path/to/interactive.md" # "interactive" で必要
```

それで、問題文側では `{@samples.sample_00}` みたいに呼び出すことでよしなに入出力 (もしくは、インタラクティブの md) を貼り付ける感じ。in と out で 2 回似たようなのを書く必要はないし、今よりはマシになりそう。

**Comment by tsutaj** [comment]
https://github.com/tsutaj/statements-manager/issues/4#issuecomment-701715822

リファクタのときにでも対応すればいいかなと思う

**Comment by tsutaj** [comment]
KaTeX を使っていた理由は、たぶん `<pre><code>` で囲まれている入力形式が MathJax でレンダリングできないからだったと思うけれど、設定をいじればできる。

具体的には http://docs.mathjax.org/en/latest/options/document.html にあるように、`pre` と `code` にそれぞれ `hoge` クラスをつけて、`processHtmlClass: 'hoge'` と設定すればいい。クラスの付与さえできれば大丈夫そう。

**Comment by tsutaj** [comment]
サンプルの更新日比較は、色々つらいのでやらなくていい気がする

**Comment by tsutaj** [comment]
全部やったので close
