### ISSUE TITLE
全ての問題をまとめた HTML の出力

### ISSUE THREAD

**Issue by tsutaj** [tsutaj/statements-manager#89]
## 概要

- 全ての問題をまとめた HTML を出力したい
  - PDF にはすでにその機能があるが、荒削りなのでこの機会に直す

## 作業内容

- 「問題テンプレート」と「全体テンプレート」を用意できるようにしておく
  - 現在は問題テンプレートしかないが、これだと対応できない場合があるので増やしたい。もしくはテンプレートファイルのうちどこの部分が問題テンプレートに相当する部分なのかを書ければ、従来どおり 1 ファイルでもできそうではある
- 各問題について、HTML を作る (問題テンプレートを適用)
- HTML を結合する (全体テンプレートを適用)

## TODO

残りの対応したいこと

- [x] 問題セットファイルは指定されたときだけ作成する (いつでも動かしてしまうと、単一の問題について回すつもりでも問題セットのファイルが更新されてしまうため)
- [x] `problemset.toml` を探索しに行く (指定されたフォルダを親方向に見ていく)
  - これいる？気を遣って実装したらかえってよくなさそうな気もするので解決済み扱いにしておく
- [x] PDF 生成時の待ち秒数の設定をいい感じにしたい
- [x] assets の問題の解消 (problemset 用にコピーできるようにしたい)
- [x] ドキュメント更新
- [x] 問題セットファイルの出力場所を変更
- [x] 問題ごとに改ページが走っていない？

**Comment by tsutaj** [comment]
jinja では for 文が使えるので、こんな感じで問題セット全体の HTML が作れそう？

```
<!-- header -->
{% for problem in problemset %}
  <!-- 問題文の前に入れたい要素がここに入る -->
  {{ problem.statement }}</li>
  <!-- 問題文の後に入れたい要素がここに入る -->
{% endfor %}
<-- footer -->
```

全体的に、ちょっとインターフェースの見直しが必要かな。

**Comment by tsutaj** [comment]
テンプレート周りは以下のように設定するように変えたい

### 設定ファイル

- 親ディレクトリに設置する `problemset.toml` でテンプレート周りの設定をする
  - これが各問題のテンプレートでもあるし、問題セット全体のテンプレートでもある
- 子ディレクトリ (各問題のディレクトリ) では、テンプレートの設定は行わない
  - 問題セットは同一のコンテストサイトに対して用意するものなので、問題ごとに個別に設定できる必要はなさそう

### 内部実装

- 以下の変数を持てるようにする
  - 生成するのは問題セットか、個別の問題か
  - 各問題の情報
    - 問題文本体
    - 言語 (日本語か英語か)

**Comment by tsutaj** [comment]
残りの対応したいこと

- [ ] 問題セットファイルは指定されたときだけ作成する (いつでも動かしてしまうと、単一の問題について回すつもりでも問題セットのファイルが更新されてしまうため)
- [ ] `problemset.toml` を探索しに行く (指定されたフォルダを親方向に見ていく)
- [ ] PDF 生成時の待ち秒数の設定をいい感じにしたい
- [ ] assets の問題の解消 (problemset 用にコピーできるようにしたい)
- [ ] ドキュメント更新

**Comment by tsutaj** [comment]
最低限の実装はできたので、ここまでで PR を作る

**Comment by tsutaj** [comment]
WORKING_DIR と同じ階層に `problemset.html` を出すようにしているが、これを変更したい。以下のような感じになるかな？

- WORKING_DIR と同じ階層に `ss-out/problemset` ディレクトリを作る
- そのディレクトリの中に `problemset.html` と assets が格納される

**Comment by tsutaj** [comment]
PDF 出力の諸々の設定は `problemset.toml` に書けるようにしたい。任意のパラメータを渡せるようにしていいのかどうかはよくわからないけど

**Comment by tsutaj** [comment]
PDF の設定を `problemset.toml` に書けるようにした。wkhtmltopdf に渡せる設定パラメータを自由にここに書くことができる

**Comment by tsutaj** [comment]
> 問題ごとに改ページが走っていない？

CSS で `page-break-after: always;` を指定したらいけた

**Comment by tsutaj** [comment]
> assets の問題の解消 (problemset 用にコピーできるようにしたい)

problemset の成果物は以下のように出力したい

```
- problemset/
  |
  |- problemset.(html|pdf|md)
  |
  |- assets/
  |  |- A/ (A 問題に関連する添付ファイル群)
     |
     |- B/ (B 問題に関連する添付ファイル群)
     |
     ...
```

これを実現するには、問題文の HTML 中に登場する、assets 内のファイルへのパス `assets/object_name` を、`assets/PROBLEM_ID/object_name` に変更しなければならない。以下のようにして行う。

- HTML を [PyQuery](https://pythonhosted.org/pyquery/) に突っ込んで DOM Object `dom` にする
- `dom` の中身を走査して、`img` タグの `src` attr をいじる (文字列の置換で対応できそう)
- `dom.html()` で HTML 化する

**Comment by tsutaj** [comment]
HTML でも PDF でも、画像つきの問題が存在したとしても problemset を出力できるようになった。 59d36e81d4bcc724e5a8000c5f0648b9cf15f511

pdfkit は絶対パスにしないとローカルにあるものを読み込んでくれないらしいので、PDF を作る直前でだけ絶対パスにするようにした。`enable-local-file-access` というオプションはあるけど何もしてくれなかった。ここでかなりハマった・・・

**Comment by tsutaj** [comment]
PR 作って差分を確認する
